name: emerald
version: 0.0.0
description: >
  Emerald language website.
author: Andrew McBurney <andrewrobertmcburney@gmail.com>
homepage: https://emerald-lang.github.io/website/
documentation: https://github.com/emerald-lang/docs
dependencies:
  args: "^0.13.6"
  html: "^0.13.0"
  meta: "^1.0.4"
  yaml: '^2.1.11'
dev_dependencies:
  test: "^0.12.15+2"
